### ISSUE TITLE
Dynamics paths does not generate static pages

### ISSUE THREAD

**Issue by prakash13t** [aiji42/next-qs-props#33] opened 2021-12-14 01:51 UTC
Hi @aiji42 ,

I download this repo and run npm build and encountered the below error.
`Error: Export encountered errors on following paths:
        /with-query-string/[...path]: /with-query-string/example/_query.{"color"|||"black"}
        /with-query-string/[...path]: /with-query-string/example/_query.{"color"|||"blue"}
        /with-query-string/[...path]: /with-query-string/example/_query.{"color"|||"red"}
        /with-query-string/[...path]: /with-query-string/example/_query.{"color"|||"white"}
        /with-query-string/[...path]: /with-query-string/example/_query.{"size"|||"large","color"|||"black"}
        /with-query-string/[...path]: /with-query-string/example/_query.{"size"|||"large","color"|||"blue"}
        /with-query-string/[...path]: /with-query-string/example/_query.{"size"|||"large","color"|||"red"}
        /with-query-string/[...path]: /with-query-string/example/_query.{"size"|||"large","color"|||"white"}
        /with-query-string/[...path]: /with-query-string/example/_query.{"size"|||"large"}`

**Comment by aiji42** [comment] 2021-12-14 13:33
Hi @prakash13t,

Please provide some more information. Are you sure that you have tried to build the example directory of this repository? Also, please tell me the environment in which you ran the build. Did you run it on your local PC such as Mac or Linux? Or is it SaaS, such as Vercel, Netlify, Amplify, etc.? What version of OS and Node do you use?

**Comment by prakash13t** [comment] 2021-12-14 16:50
Hi @aiji42 ,

Yes, I downloaded it on my local desktop and run the build for example folder.

**Comment by aiji42** [comment] 2021-12-16 14:14
Unfortunately, I can't reproduce this on my local and Vercel, so I have no way to investigate further.

I am currently working on version 2.0.0 of this library, which will change the path structure significantly. I'm hoping that this problem will be resolved in the process.

**Closed as completed** 2022-01-21 13:45 UTC
